### ISSUE TITLE
Rari: Handle Rari Performance Fees

### ISSUE THREAD

**Issue by RedFox20** [tempus-finance/tempus-protocol#474]
These fees are accumulated and are distributed by minting more shares.

**Comment by yuval-weiss** [comment]
Our current implementation take the performance fee into account. We're using [getFundBalance](https://github.com/Rari-Capital/rari-stable-pool-contracts/blob/7f351ca3df72a0196f3640f30a6db73660ab1467/contracts/RariFundManager.sol#L481) rather than [getRawFundBalance](https://github.com/Rari-Capital/rari-stable-pool-contracts/blob/7f351ca3df72a0196f3640f30a6db73660ab1467/contracts/RariFundManager.sol#L420).

**Comment by yuval-weiss** [comment]
Our current implementation take the performance fee into account. We're using [getFundBalance](https://github.com/Rari-Capital/rari-stable-pool-contracts/blob/7f351ca3df72a0196f3640f30a6db73660ab1467/contracts/RariFundManager.sol#L481) rather than [getRawFundBalance](https://github.com/Rari-Capital/rari-stable-pool-contracts/blob/7f351ca3df72a0196f3640f30a6db73660ab1467/contracts/RariFundManager.sol#L420).
